PlaylistGenerator/Web/PlaylistGenerator.Web/Models/Genre/CollectionGenresFullViewModels.cs
using System.Collections.Generic;

namespace PlaylistGenerator.Web.Models.Genre
{
    public class CollectionGenresFullViewModels
    {
        public IEnumerable<GenreFullViewModel> Collection { get; set; }
    }
}

PlaylistGenerator/Web/PlaylistGenerator.Web/Models/Genre/GenreFullViewModel.cs
using System;

namespace PlaylistGenerator.Web.Models.Genre
{
    public class GenreFullViewModel
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        public string PictureURL { get; set; }

        public bool IsSelected { get; set; }
    }
}

PlaylistGenerator/Web/PlaylistGenerator.Web/Models/Playlist/CollectionPlaylistLightViewModels.cs
using PlaylistGenerator.Web.Models.Contracts;
using PlaylistGenerator.Web.Models.Genre;
using System;
using System.Collections.Generic;

namespace PlaylistGenerator.Web.Models.Playlist
{
    public class CollectionPlaylistLightViewModels : IPagingCollection
    {
        public string Url { get; set; }

        public IEnumerable<PlaylistLightViewModel> CollectionPlaylists { get; set; }

        public IEnumerable<PlaylistLightViewModel> CollectionPlaylistsByPage { get; set; }

        public string NameToSearchForFilter { get; set; }

        public int DurationMinHoursFilter { get; set; }

        public int DurationMaxHoursFilter { get; set; }

        public int RankMinFilter { get; set; }

        public int RankMaxFilter { get; set; }

        public List<GenreFullViewModel> Genres { get; set; }

        public List<Guid> GenresIdChosenByUserFilter { get; set; }

        public SortMethod SortMethod { get; set; }

        public SortOrder SortOrder { get; set; }

        public bool IsAscending { get; set; }

        public int PageSize { get; set; }

        public int CurrentPage { get; set; }

        public int TotalCount { get; set; }

        public int FirstPage => 1;

        public int LastPage
        {
            get
            {
                return (int)Math.Ceiling((double)this.TotalCount / this.PageSize);
            }
        }

        public int PreviousPage => this.CurrentPage - 1;

        public int NextPage => this.CurrentPage + 1;

        public bool IsPreviousPageDisabled => this.CurrentPage == 1;

        public bool IsNextPageDisabled
        {
            get
            {
                return CurrentPage == Math.Ceiling((double)this.TotalCount / this.PageSize);
            }
        }
    }

    public enum SortMethod
    {
        Sort = 0,
        Rank = 1,
        Duration = 2,
        Name = 3
    }

    public enum SortOrder
    {
        Order = 0,
        Desc = 1,
        Asc = 2,
    }
}

PlaylistGenerator/Web/PlaylistGenerator.Web/Models/Playlist/PlaylistCreateFormViewModel.cs
using Microsoft.AspNetCore.Http;
using PlaylistGenerator.Web.Models.Genre;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PlaylistGenerator.Web.Models.Playlist
{
    public class PlaylistCreateFormViewModel
    {
        [Required]
        [MinLength(2)]
        [MaxLength(50)]
        public string Name { get; set; }

        [MaxLength(500)]
        public string Description { get; set; }

        public IFormFile ImageFile { get; set; }

        public bool IsTopTracksOptionEnabled { get; set; }

        public bool IsTracksFromSameArtistEnabled { get; set; }

        public List<GenreFullViewModel> Genres { get; set; }

        public List<Guid> GenresIdChosenByUser { get; set; }

        public string PointFirstQueryString { get; set; }

        public string PointSecondQueryString { get; set; }
    }
}

PlaylistGenerator/Web/PlaylistGenerator.Web/Models/Playlist/PlaylistFullViewModel.cs
using Microsoft.AspNetCore.Http;
using PlaylistGenerator.Web.Models.Contracts;
using PlaylistGenerator.Web.Models.Genre;
using PlaylistGenerator.Web.Models.Song;
using System;
using System.Collections.Generic;

namespace PlaylistGenerator.Web.Models.Playlist
{
    public class PlaylistFullViewModel : IDeletable
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public DateTime? DateCreated { get; set; }

        public DateTime? DateModified { get; set; }

        public string Image { get; set; }

        public double Rank { get; set; }

        public int DurationPlaylist { get; set; }

        public int DurationTravel { get; set; }

        public bool IsDeleted { get; set; }

        public bool IsUnlisted { get; set; }

        public int GenresCount { get; set; }

        public int SongsCount { get; set; }

        public Guid UserId { get; set; }
        public string UserName { get; set; }
        public string UserImage { get; set; }

        public IEnumerable<SongLightViewModel> Songs { get; set; }

        public IEnumerable<SongLightViewModel> SongsTop3 { get; set; }

        public IEnumerable<GenreFullViewModel> Genres { get; set; }

        public IEnumerable<PlaylistFullViewModel> PlaylistsSimilar { get; set; }

        public IFormFile ImageFile { get; set; }

        public string NameController { get; set; }

        public bool IsToBeDeletedByAdmin { get; set; }

        public int CurrentPage { get; set; }
    }
}

PlaylistGenerator/Web/PlaylistGenerator.Web/Models/Playlist/PlaylistLightViewModel.cs
using PlaylistGenerator.Web.Models.Contracts;
using System;

namespace PlaylistGenerator.Web.Models.Playlist
{
    public class PlaylistLightViewModel : IDeletable
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public DateTime? DateCreated { get; set; }

        public DateTime? DateModified { get; set; }

        public string Image { get; set; }

        public double Rank { get; set; }

        public int DurationPlaylist { get; set; }

        public int DurationTravel { get; set; }

        public bool IsDeleted { get; set; }

        public bool IsUnlisted { get; set; }

        public int GenresCount { get; set; }

        public int SongsCount { get; set; }

        public Guid UserId { get; set; }
        public string UserName { get; set; }
        public string UserImage { get; set; }

        public string NameController { get; set; }

        public bool IsToBeDeletedByAdmin { get; set; }

        public int CurrentPage { get; set; }
    }
}

PlaylistGenerator/Web/PlaylistGenerator.Web/Controllers/AdminsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PlaylistGenerator.Data.Models;
using PlaylistGenerator.Services.Contracts;
using PlaylistGenerator.Web.Models.Playlist;
using PlaylistGenerator.Web.Models.Syncronization;
using PlaylistGenerator.Web.Models.User;
using System.Linq;
using System.Threading.Tasks;

namespace PlaylistGenerator.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminsController : Controller
    {
        private readonly IUserService userService;
        private readonly IPlaylistService playlistService;
        private readonly IGenreService genreService;
        private readonly ISongService songService;
        private readonly ISyncronizationService syncronizationService;
        private readonly IMapper mapper;
        private readonly UserManager<User> userManager;


        public AdminsController(IUserService userService, IPlaylistService playlistService, IGenreService genreService, ISongService songService, ISyncronizationService syncronizationService, UserManager<User> userManager, IMapper mapper)
        {
            this.userService = userService;
            this.playlistService = playlistService;
            this.genreService = genreService;
            this.songService = songService;
            this.syncronizationService = syncronizationService;
            this.userManager = userManager;
            this.mapper = mapper;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Genres()
        {
            var lastSyncronization = await this.syncronizationService.GetLastSyncronizationAsync();
            var model = this.mapper.Map<SyncronizationViewModel>(lastSyncronization);
            return await Task.Run(() => View(model));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> UpdateGenres()
        {
            await this.syncronizationService.SyncronizeGenresAndSongsAsync();
            var lastSyncronization = await this.syncronizationService.GetLastSyncronizationAsync();
            var model = this.mapper.Map<SyncronizationViewModel>(lastSyncronization);

            return this.View("Genres", model);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Playlists(int page = 1)
        {
            int pageCountSize = 12;

            var collectionPlaylistsServiceModels = await playlistService.GetAllPlaylistsAsync(false, null, true);

            int totalCount = collectionPlaylistsServiceModels.Count();

            var collectionPlaylistsServiceModelsByPage = collectionPlaylistsServiceModels
                .Skip((page - 1) * pageCountSize)
                .Take(pageCountSize);

            var model = new CollectionPlaylistLightViewModels
            {
                CollectionPlaylists = collectionPlaylistsServiceModelsByPage.Select(x => new PlaylistLightViewModel
                {
                    Id = x.Id,
                    Name = x.Name,
                    Description = x.Description,
                    DateCreated = x.DateCreated,
                    DateModified = x.DateModified,
                    GenresCount = x.GenresCount,
                    SongsCount = x.SongsCount,
                    IsUnlisted = x.IsUnlisted,
                    IsDeleted = x.IsDeleted,
                    Image = x.Image,
                    DurationPlaylist = x.DurationPlaylist,
                    DurationTravel = x.DurationTravel,
                    Rank = x.Rank,
                    UserId = x.UserId,
                    UserImage = x.UserImage,
                    UserName = x.UserName,
                }),
                PageSize = pageCountSize,
                CurrentPage = page,
                TotalCount = totalCount,
                Url = "/Admins/Playlists"
            };

            return await Task.Run(() => View(model));
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Users(int page = 1)
        {
            var collectionUsersServiceModels = await userService.GetAllUsersAsync(true, page);
            var pageSizeCount = this.userService.GetPageCountSizing();
            var totalCount = this.userService.GetTotalUsersCount();

            var model = new CollectionUserFullViewModels
            {
                Users = collectionUsersServiceModels.Select(x => new UserFullViewModel
                {
                    Id = x.Id,
                    FirstName = x.FirstName,
                    LastName = x.LastName,
                    DateCreated = x.DateCreated,
                    DateModified = x.DateModified,
                    IsAdmin = x.IsAdmin,
                    IsBanned = x.IsBanned,
                    IsDeleted = x.IsDeleted,
                    Image = x.Image,
                    PlaylistsCount = x.PlaylistsCount,
                    ApiKey = x.ApiKey
                }),
                PageSize = pageSizeCount,
                CurrentPage = page,
                TotalCount = totalCount,
                Url = "/Admins/Users"
            };

            return this.View(model);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Welcome()
        {
            return await Task.Run(() => View());
        }
    }
}

PlaylistGenerator/Web/PlaylistGenerator.Web/Controllers/GenresController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using PlaylistGenerator.Services.Contracts;
using PlaylistGenerator.Web.Models.Genre;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace PlaylistGenerator.Web.Controllers
{
    public class GenresController : Controller
    {
        private readonly IGenreService genreService;
        private readonly IMapper mapper;

        public GenresController(IGenreService genreService, IMapper mapper)
        {
            this.genreService = genreService;
            this.mapper = mapper;
        }

        public async Task<IActionResult> All()
        {
            var genres = await this.genreService.GetAllGenresAsync();

            var genreLightViewModels = this.mapper.Map<IEnumerable<GenreFullViewModel>>(genres);

            var model = new CollectionGenresFullViewModels
            {
                Collection = genreLightViewModels
            };

            return this.View(model);
        }
    }
}

PlaylistGenerator/Web/PlaylistGenerator.Web/Controllers/UsersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PlaylistGenerator.Data.Models;
using PlaylistGenerator.Services.Contracts;
using PlaylistGenerator.Services.Models;
using PlaylistGenerator.Services.Models.Genre;
using PlaylistGenerator.Services.Models.User;
using PlaylistGenerator.Web.Models.Genre;
using PlaylistGenerator.Web.Models.Playlist;
using PlaylistGenerator.Web.Models.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlaylistGenerator.Web.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly SignInManager<User> signInManager;
        private readonly IMapper mapper;
        private readonly IUserService userService;
        private readonly IGenreService genreService;
        private readonly IPlaylistService playlistService;

        public UsersController(UserManager<User> userManager, SignInManager<User> signInManager, IUserService userService, IPlaylistService playlistService, IGenreService genreService, IMapper mapper)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.userService = userService;
            this.playlistService = playlistService;
            this.genreService = genreService;
            this.mapper = mapper;
        }

        [Authorize]
        public async Task<IActionResult> All(int page = 1)
        {
            IEnumerable<UserServiceModel> collectionUserServiceModels = await userService.GetAllUsersAsync(false, page);
            int pageSizeCount = this.userService.GetPageCountSizing();
            int totalCount = this.userService.GetTotalUsersCount();

            CollectionUserFullViewModels model = new CollectionUserFullViewModels();

            model.Users = collectionUserServiceModels.Select(x => new UserFullViewModel
            {
                Id = x.Id,
                FirstName = x.FirstName,
                LastName = x.LastName,
                DateCreated = x.DateCreated,
                DateModified = x.DateModified,
                IsBanned = x.IsBanned,
                IsAdmin = x.IsAdmin,
                IsDeleted = x.IsDeleted,
                Image = x.Image,
                PlaylistsCount = x.PlaylistsCount,
            });

            model.Url = "/Users/All";
            model.PageSize = pageSizeCount;
            model.CurrentPage = page;
            model.TotalCount = totalCount;

            return this.View(model);
        }

        [Authorize]
        public async Task<IActionResult> UserById(Guid id)
        {
            UserServiceModel userServiceModel = await userService.GetUserByIdAsync(id);

            UserFullViewModel model = this.mapper.Map<UserFullViewModel>(userServiceModel);

            if (userServiceModel.PlaylistsCount != 0)
            {
                IEnumerable<PlaylistServiceModel> playlistsServicesOfUser = await playlistService.GetPlaylistsByUserIdAsync(id);

                IEnumerable<Guid> playlistsIdsOfUser = playlistsServicesOfUser.Select(x => x.Id);

                HashSet<GenreServiceModel> genresPreferred = new HashSet<GenreServiceModel>();

                foreach (var playlistId in playlistsIdsOfUser)
                {
                    var genresOfPlaylists = await genreService.GetGenresByPlaylistId(playlistId);

                    foreach (var genre in genresOfPlaylists)
                    {
                        if (!genresPreferred.Any(x => x.Id == genre.Id))
                        {
                            genresPreferred.Add(genre);
                        }
                    }
                }

                model.Playlists = this.mapper.Map<IEnumerable<PlaylistLightViewModel>>(playlistsServicesOfUser);
                model.GenresPreferred = this.mapper.Map<IEnumerable<GenreFullViewModel>>(genresPreferred);
            }

            return this.View(model);
        }

        public async Task<IActionResult> Remove(Guid id, bool isRemovedByAdmin, int page = 1)
        {
            await userService.DeleteUserAsync(id);

            if (isRemovedByAdmin)
            {
                return Redirect($"/Admins/Users?page={page}");
            }
            return Redirect($"/Users/All?page={page}");
        }

        public async Task<IActionResult> SwapBanStatus(Guid id, bool isSwappedByAdmin, int page = 1)
        {
            await userService.SwapUserBanStatusByIdAsync(id);

            if (isSwappedByAdmin)
            {
                return Redirect($"/Admins/Users?page={page}");
            }
            return Redirect($"/Users/All?page={page}");
        }
    }
}

PlaylistGenerator/Web/PlaylistGenerator.Web/Views/Admins/Genres.cshtml
@model PlaylistGenerator.Web.Models.Syncronization.SyncronizationViewModel
@{
    ViewData["Title"] = "Genres";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h1>Genres</h1>*@

<partial name="_AdminsPartial" />

<input type="button" class="btn btn-primary btn-round" id="updateGenresButton" value="Syncronize Genres" onclick="disableUpdateGenresButton(); displayBusyIndicator(); window.location = '@Url.Action("UpdateGenres", "Admins")'" />
<partial name="_LoadingPartial" />

<br />

<div class="card">
    @if (Model == null)
    {
    <div class="card-header font-weight-light">
        <h5 class="card-category">No Synchronizations yet.</h5>
    </div>
    }
    else
    {
        <div class="card-header">
            <h5 class="card-category">Last Syncronization:</h5>
        </div>
        <div class="card-body">
            <table class="table table w-75">
                <thead>
                    <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Status</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Model.Date UTC</td>
                        <td>
                            @if (Model.IsComplete)
                            {
                                <b>Complete</b>
                            }
                            else if (Model.WasInterrupted)
                            {
                                <b>Interrupted</b>
                            }
                            else
                            {
                                <b>In Progress</b>
                            }
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    }
</div>

PlaylistGenerator/Web/PlaylistGenerator.Web/Views/Admins/Playlists.cshtml
@model PlaylistGenerator.Web.Models.Playlist.CollectionPlaylistLightViewModels

@{
    int num = 0;
}

@{
    ViewData["Title"] = "Playlists";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<partial name="_AdminsPartial" />

<partial name="_PageNavigatorPartial" model="@Model" />

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title"> Playlists</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table tablesorter " id="">
                        <thead class=" text-primary">
                            <tr>
                                <th>
                                    #
                                </th>
                                <th>
                                    Image
                                </th>
                                <th>
                                    Name
                                </th>
                                <th>
                                    <i class="tim-icons icon-calendar-60"></i> Created
                                </th>
                                <th>
                                    <i class="tim-icons icon-calendar-60"></i> Modified
                                </th>
                                <th>
                                    User
                                </th>
                                <th>
                                    <i class="tim-icons icon-time-alarm"></i> Travel
                                </th>
                                <th>
                                    <i class="tim-icons icon-time-alarm"></i> Playlist
                                </th>
                                <th>
                                    Count Genres
                                </th>
                                <th>
                                    Count Songs
                                </th>
                                <th>
                                    Rank
                                </th>
                                <th class="text-center">
                                    Update
                                </th>
                                <th class="text-center">
                                    List / Unlist
                                </th>
                                <th class="text-center">
                                    Delete
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.CollectionPlaylists)
                            {
                                num++;
                                <tr>
                                    <td>
                                        @(num + (@Model.CurrentPage * Model.PageSize) - Model.PageSize)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("PlaylistById", "Playlists", new { id = item.Id })"><img src="@item.Image" id="img-circle" height="50"></a>
                                    </td>
                                    <td>
                                        <a href="@Url.Action("PlaylistById", "Playlists", new { id = item.Id })"><p>@item.Name</p></a>
                                    </td>
                                    <td>
                                        <p>@item.DateCreated</p>
                                    </td>
                                    <td>
                                        <p>@item.DateModified</p>
                                    </td>
                                    <td>
                                        <a href="@Url.Action("UserById", "Users", new { id = item.UserId })"><p><img src="@item.UserImage" id="img-circle" height="30" /> @item.UserName</p></a>
                                    </td>
                                    <td>
                                        <p>@item.DurationTravel</p>
                                    </td>
                                    <td>
                                        <p>@item.DurationPlaylist</p>
                                    </td>
                                    <td>
                                        <p>@item.GenresCount</p>
                                    </td>
                                    <td>
                                        <p>@item.SongsCount</p>
                                    </td>
                                    <td>
                                        <p>@item.Rank.ToString("F0")</p>
                                    </td>
                                    <td class="text-center">
                                        <button type="button" class="btn btn-primary btn-round" onclick="window.location='@Url.Action("Update", "Playlists", new { id = item.Id })'"><i class="tim-icons icon-pencil"></i></button>
                                    </td>
                                    <td class="text-center">
                                        @if (item.IsUnlisted)
                                        {
                                            <button type="button" class="btn btn-success btn-round" onclick="window.location='@Url.Action("SwapUnlistedStatus", "Playlists", new { id = item.Id, isSwappedByAdmin = true, page = Model.CurrentPage })'"><i class="tim-icons icon-simple-add"></i></button>
                                        }
                                        else
                                        {
                                            <button type="button" class="btn btn-warning btn-round" onclick="window.location='@Url.Action("SwapUnlistedStatus", "Playlists", new { id = item.Id, isSwappedByAdmin = true, page = Model.CurrentPage })'"><i class="tim-icons icon-simple-remove"></i></button>
                                        }
                                    </td>
                                    <td class="text-center">
                                        @{
                                            item.IsToBeDeletedByAdmin = true;
                                            item.NameController = "Playlists";
                                            item.CurrentPage = Model.CurrentPage;
                                        }
                                        <partial name="_DeleteModalPartial" model="@item" />
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<br />

PlaylistGenerator/Web/PlaylistGenerator.Web/Views/Admins/UpdateGenres.cshtml
@model PlaylistGenerator.Web.Models.Syncronization.SyncronizationViewModel
@{
    ViewData["Title"] = "Genres";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h1>Genres</h1>*@

<!--<partial name="_AdminsPartial" />

@if(Model == null)
{
    <b>No syncronizations have been made so far.</b>
}else 
{ 
<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Status</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>@Model.Date</td>
            <td>
                @(Model.WasInterrupted ? "Interrupted" : "");
                @(Model.IsComplete ? "Complete" : "");
            </td>
        </tr>
    </tbody>
</table>
}-->