PlaylistGenerator/Web/PlaylistGenerator.Web/Models/Playlist/CollectionPlaylistLightViewModels.cs
using PlaylistGenerator.Web.Models.Contracts;
using PlaylistGenerator.Web.Models.Genre;
using System;
using System.Collections.Generic;

namespace PlaylistGenerator.Web.Models.Playlist
{
    public class CollectionPlaylistLightViewModels : IPagingCollection
    {
        public string Url { get; set; }

        public IEnumerable<PlaylistLightViewModel> CollectionPlaylists { get; set; }

        public IEnumerable<PlaylistLightViewModel> CollectionPlaylistsByPage { get; set; }

        public string NameToSearchForFilter { get; set; }

        public int DurationMinHoursFilter { get; set; }

        public int DurationMaxHoursFilter { get; set; }

        public int RankMinFilter { get; set; }

        public int RankMaxFilter { get; set; }

        public List<GenreFullViewModel> Genres { get; set; }

        public List<Guid> GenresIdChosenByUserFilter { get; set; }

        public SortMethod SortMethod { get; set; }

        public SortOrder SortOrder { get; set; }

        public bool IsAscending { get; set; }

        public int PageSize { get; set; }

        public int CurrentPage { get; set; }

        public int TotalCount { get; set; }

        public int FirstPage => 1;

        public int LastPage
        {
            get
            {
                return (int)Math.Ceiling((double)this.TotalCount / this.PageSize);
            }
        }

        public int PreviousPage => this.CurrentPage - 1;

        public int NextPage => this.CurrentPage + 1;

        public bool IsPreviousPageDisabled => this.CurrentPage == 1;

        public bool IsNextPageDisabled
        {
            get
            {
                return CurrentPage == Math.Ceiling((double)this.TotalCount / this.PageSize);
            }
        }
    }

    public enum SortMethod
    {
        Sort = 0,
        Rank = 1,
        Duration = 2,
        Name = 3
    }

    public enum SortOrder
    {
        Order = 0,
        Desc = 1,
        Asc = 2,
    }
}

PlaylistGenerator/Web/PlaylistGenerator.Web/Models/Playlist/PlaylistCreateFormViewModel.cs
using Microsoft.AspNetCore.Http;
using PlaylistGenerator.Web.Models.Genre;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PlaylistGenerator.Web.Models.Playlist
{
    public class PlaylistCreateFormViewModel
    {
        [Required]
        [MinLength(2)]
        [MaxLength(50)]
        public string Name { get; set; }

        [MaxLength(500)]
        public string Description { get; set; }

        public IFormFile ImageFile { get; set; }

        public bool IsTopTracksOptionEnabled { get; set; }

        public bool IsTracksFromSameArtistEnabled { get; set; }

        public List<GenreFullViewModel> Genres { get; set; }

        public List<Guid> GenresIdChosenByUser { get; set; }

        public string PointFirstQueryString { get; set; }

        public string PointSecondQueryString { get; set; }
    }
}

PlaylistGenerator/Web/PlaylistGenerator.Web/Controllers/PlaylistsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PlaylistGenerator.Data.Models;
using PlaylistGenerator.Services.Contracts;
using PlaylistGenerator.Services.Models;
using PlaylistGenerator.Web.Controllers.Extensions;
using PlaylistGenerator.Web.Models;
using PlaylistGenerator.Web.Models.Genre;
using PlaylistGenerator.Web.Models.Playlist;
using PlaylistGenerator.Web.Models.Song;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlaylistGenerator.Web.Controllers
{
    public class PlaylistsController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly SignInManager<User> signInManager;
        private readonly IPlaylistService playlistService;
        private readonly IGenreService genreService;
        private readonly ISongService songService;
        private readonly IUserService userService;
        private readonly IMapper mapper;

        public PlaylistsController(UserManager<User> userManager, SignInManager<User> signInManager, IPlaylistService playlistService, IGenreService genreService, ISongService songService, IUserService userService, IMapper mapper)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.playlistService = playlistService;
            this.genreService = genreService;
            this.songService = songService;
            this.userService = userService;
            this.mapper = mapper;
        }

        public async Task<IActionResult> All(int page = 1)
        {
            int pageCountSize = 12;

            IEnumerable<PlaylistServiceModel> collectionPlaylistsServiceModels = await playlistService.GetAllPlaylistsAsync(false, null, false);

            int totalCount = collectionPlaylistsServiceModels.Count();

            var collectionPlaylistsServiceModelsByPage = collectionPlaylistsServiceModels
                .OrderByDescending(x => x.Rank)
                .Skip((page - 1) * pageCountSize)
                .Take(pageCountSize);

            CollectionPlaylistLightViewModels model = new CollectionPlaylistLightViewModels();
            model.CollectionPlaylists = this.mapper.Map<IEnumerable<PlaylistLightViewModel>>(collectionPlaylistsServiceModelsByPage);

            model.Url = "/Playlists/All";
            model.PageSize = pageCountSize;
            model.CurrentPage = page;
            model.TotalCount = totalCount;

            var genresServiceModels = await genreService.GetAllGenresAsync(false, null);
            model.Genres = this.mapper.Map<IEnumerable<GenreFullViewModel>>(genresServiceModels).ToList();

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> All(CollectionPlaylistLightViewModels input)
        {
            IEnumerable<PlaylistServiceModel> playlists;

            if (input.NameToSearchForFilter != null)
            {
                // Filter By Name
                playlists = await playlistService.GetPlaylistsByNameContainsSubstring(input.NameToSearchForFilter);
            }
            else
            {
                playlists = await playlistService.GetAllPlaylistsAsync(false, null, false);

                // Filter By Duration
                if (input.DurationMinHoursFilter != 0 || input.DurationMaxHoursFilter != 0)
                {
                    playlists = playlistService.FilterByRange(playlists, "duration", input.DurationMinHoursFilter, input.DurationMaxHoursFilter);
                }

                // Filter By Rank
                if (input.RankMinFilter != 0 || input.RankMaxFilter != 0)
                {
                    playlists = playlistService.FilterByRange(playlists, "rank", input.RankMinFilter, input.RankMaxFilter);
                }

                // Filter By Genres
                if (input.Genres != null && input.Genres.Count() != 0)
                {
                    var genresIdsChosenByUser = input.Genres.Where(x => x.IsSelected == true).Select(y => y.Id);
                    playlists = playlistService.FilterByGenre(playlists, genresIdsChosenByUser);
                }

                // Sort
                string sortMethod = input.SortMethod.ToString().ToLowerInvariant();
                string sortOrder = input.SortOrder.ToString().ToLowerInvariant();

                if (sortMethod == "sort")
                {
                    sortMethod = "rank";
                }
                if (sortOrder == "order")
                {
                    sortOrder = "desc";
                }

                playlists = playlistService.Sort(playlists, sortMethod, sortOrder);
            }

            CollectionPlaylistLightViewModels model = new CollectionPlaylistLightViewModels();
            model.CollectionPlaylists = this.mapper.Map<IEnumerable<PlaylistLightViewModel>>(playlists);
            
            var genresServiceModels = await genreService.GetAllGenresAsync(false, null);
            model.Genres = this.mapper.Map<IEnumerable<GenreFullViewModel>>(genresServiceModels).ToList();

            model.CurrentPage = 1;
            model.Url = "/Playlists/All";

            return this.View(model);
        }

        public async Task<IActionResult> MyPlaylists(string email)
        {
            var user = await userService.GetUserByEmailAsync(email);
            var collectionPlaylistsByUserId = await playlistService.GetPlaylistsByUserIdAsync(user.Id);
            CollectionPlaylistLightViewModels model = new CollectionPlaylistLightViewModels();
            model.CollectionPlaylists = this.mapper.Map<IEnumerable<PlaylistLightViewModel>>(collectionPlaylistsByUserId);

            return this.View(model);
        }

        public async Task<IActionResult> PlaylistById(Guid id)
        {
            var playlistServiceModel = await playlistService.GetPlaylistByIdAsync(id);

            var songs = await songService.GetSongsByPlaylistIdAsync(playlistServiceModel.Id);
            var genres = await genreService.GetGenresByPlaylistId(playlistServiceModel.Id);

            var durationPlaylist = playlistServiceModel.DurationPlaylist;
            var durationRangeMin = durationPlaylist - (1 /*hour*/ * 60 /*minutes*/ * 60 /*seconds*/);
            var durationRangeMax = durationPlaylist = (1 /*hour*/ * 60 /*minutes*/ * 60 /*seconds*/);

            var playlistsAll = await playlistService.GetAllPlaylistsAsync();
            playlistsAll = playlistService.FilterByRange(playlistsAll, "duration", durationRangeMin, durationRangeMax);
            playlistsAll = playlistService.FilterByGenre(playlistsAll, genres.Select(x => x.Id));
            var playlistsSimilarTop5 = playlistsAll.Where(x => x.Id != playlistServiceModel.Id).OrderBy(x => x.Rank).Take(3);

            var model = this.mapper.Map<PlaylistFullViewModel>(playlistServiceModel);
            model.Songs = this.mapper.Map<IEnumerable<SongLightViewModel>>(songs);
            model.SongsTop3 = this.mapper.Map<IEnumerable<SongLightViewModel>>(songs.OrderBy(x => x.Rank).Take(3));
            model.Genres = this.mapper.Map<IEnumerable<GenreFullViewModel>>(genres);
            model.PlaylistsSimilar = this.mapper.Map<IEnumerable<PlaylistFullViewModel>>(playlistsSimilarTop5);
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Create()
        {
            var genresServiceModels = await genreService.GetAllGenresAsync(false, null);
            var genreViewModels = this.mapper.Map<IEnumerable<GenreFullViewModel>>(genresServiceModels).ToList();

            PlaylistCreateFormViewModel model = new PlaylistCreateFormViewModel
            {
                Genres = genreViewModels
            };

            return await Task.Run(() => View(model));
        }

        [HttpPost]
        [Authorize]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PlaylistCreateFormViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var userDataModel = await this.userManager.GetUserAsync(this.User);
            var userServiceModel = await this.userService.GetUserByIdAsync(userDataModel.Id);

            // Create new Playlist in Database (no Image, no DurationTravel).
            PlaylistServiceModel playlistToCreate = new PlaylistServiceModel
            {
                Name = input.Name,
                Description = input.Description,
                UserId = userServiceModel.Id,
                UserName = userServiceModel.FirstName + " " + userServiceModel.LastName,
                UserImage = userServiceModel.Image,
            };
            PlaylistServiceModel playlistCreated = await playlistService.CreatePlaylistAsync(playlistToCreate);

            // Upload image and save it in wwwroot.
            await ControllerExtensionMethods.UploadImageFile(playlistToCreate.Id, "playlists", input.ImageFile, true);

            // Set image path to Playlist as Image property.
            await playlistService.UpdatePlaylistImageAsync(playlistCreated.Id);

            //Get DurationTravel from Bing Location API.
            int durationTravel = await playlistService.GetDurationTravelAsync(input.PointFirstQueryString, input.PointSecondQueryString);
            await playlistService.UpdatePlaylistDurationTravelAsync(playlistCreated.Id, durationTravel);

            // Get Genres From input parameter.
            var genresIdsChosenByUser = input.Genres.Where(x => x.IsSelected == true).Select(y => y.Id);

            bool isMissionAccomplished = await playlistService.GeneratePlaylistAsync(playlistCreated.Id, durationTravel, genresIdsChosenByUser, input.IsTopTracksOptionEnabled, input.IsTracksFromSameArtistEnabled);

            return RedirectToAction("Success", "Home", new SuccessViewModel

PlaylistGenerator/Web/PlaylistGenerator.Web/Controllers/UsersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PlaylistGenerator.Data.Models;
using PlaylistGenerator.Services.Contracts;
using PlaylistGenerator.Services.Models;
using PlaylistGenerator.Services.Models.Genre;
using PlaylistGenerator.Services.Models.User;
using PlaylistGenerator.Web.Models.Genre;
using PlaylistGenerator.Web.Models.Playlist;
using PlaylistGenerator.Web.Models.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlaylistGenerator.Web.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly SignInManager<User> signInManager;
        private readonly IMapper mapper;
        private readonly IUserService userService;
        private readonly IGenreService genreService;
        private readonly IPlaylistService playlistService;

        public UsersController(UserManager<User> userManager, SignInManager<User> signInManager, IUserService userService, IPlaylistService playlistService, IGenreService genreService, IMapper mapper)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.userService = userService;
            this.playlistService = playlistService;
            this.genreService = genreService;
            this.mapper = mapper;
        }

        [Authorize]
        public async Task<IActionResult> All(int page = 1)
        {
            IEnumerable<UserServiceModel> collectionUserServiceModels = await userService.GetAllUsersAsync(false, page);
            int pageSizeCount = this.userService.GetPageCountSizing();
            int totalCount = this.userService.GetTotalUsersCount();

            CollectionUserFullViewModels model = new CollectionUserFullViewModels();

            model.Users = collectionUserServiceModels.Select(x => new UserFullViewModel
            {
                Id = x.Id,
                FirstName = x.FirstName,
                LastName = x.LastName,
                DateCreated = x.DateCreated,
                DateModified = x.DateModified,
                IsBanned = x.IsBanned,
                IsAdmin = x.IsAdmin,
                IsDeleted = x.IsDeleted,
                Image = x.Image,
                PlaylistsCount = x.PlaylistsCount,
            });

            model.Url = "/Users/All";
            model.PageSize = pageSizeCount;
            model.CurrentPage = page;
            model.TotalCount = totalCount;

            return this.View(model);
        }

        [Authorize]
        public async Task<IActionResult> UserById(Guid id)
        {
            UserServiceModel userServiceModel = await userService.GetUserByIdAsync(id);

            UserFullViewModel model = this.mapper.Map<UserFullViewModel>(userServiceModel);

            if (userServiceModel.PlaylistsCount != 0)
            {
                IEnumerable<PlaylistServiceModel> playlistsServicesOfUser = await playlistService.GetPlaylistsByUserIdAsync(id);

                IEnumerable<Guid> playlistsIdsOfUser = playlistsServicesOfUser.Select(x => x.Id);

                HashSet<GenreServiceModel> genresPreferred = new HashSet<GenreServiceModel>();

                foreach (var playlistId in playlistsIdsOfUser)
                {
                    var genresOfPlaylists = await genreService.GetGenresByPlaylistId(playlistId);

                    foreach (var genre in genresOfPlaylists)
                    {
                        if (!genresPreferred.Any(x => x.Id == genre.Id))
                        {
                            genresPreferred.Add(genre);
                        }
                    }
                }

                model.Playlists = this.mapper.Map<IEnumerable<PlaylistLightViewModel>>(playlistsServicesOfUser);
                model.GenresPreferred = this.mapper.Map<IEnumerable<GenreFullViewModel>>(genresPreferred);
            }

            return this.View(model);
        }

        public async Task<IActionResult> Remove(Guid id, bool isRemovedByAdmin, int page = 1)
        {
            await userService.DeleteUserAsync(id);

            if (isRemovedByAdmin)
            {
                return Redirect($"/Admins/Users?page={page}");
            }
            return Redirect($"/Users/All?page={page}");
        }

        public async Task<IActionResult> SwapBanStatus(Guid id, bool isSwappedByAdmin, int page = 1)
        {
            await userService.SwapUserBanStatusByIdAsync(id);

            if (isSwappedByAdmin)
            {
                return Redirect($"/Admins/Users?page={page}");
            }
            return Redirect($"/Users/All?page={page}");
        }
    }
}

PlaylistGenerator/Web/PlaylistGenerator.Web/Views/Playlists/All.cshtml
@model PlaylistGenerator.Web.Models.Playlist.CollectionPlaylistLightViewModels

@{
    ViewData["Title"] = "All";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<partial name="_ScrollbarPartial" />

<div class="row">
    <div class="col-md-3 text-right">
        <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <form asp-controller="Playlists" asp-action="All" method="post" class="form" enctype="multipart/form-data">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <i class="tim-icons icon-simple-remove"></i>
                        </button>
                        <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH" asp-for="NameToSearchForFilter" typeof="text" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row flex-space-between">
    <div id="accordion" role="tablist" aria-multiselectable="true" class="col-md-11  card-collapse">
        <div class="card card-plain filter-container">
            <div class="card-header" role="tab" id="headingOne">
                <a class="collapsed" id="collapsable-link" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Filter Playlists

                    <i class="tim-icons icon-minimal-down"></i>
                </a>
            </div>

            <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
                <div class="card ">
                    <form asp-controller="Playlists" asp-action="All" method="post" class="form-inline filter-form" id="filterPlaylistsForm" onsubmit="displayBusyIndicator()" enctype="multipart/form-data">
                        <div asp-validation-summary="All" class="text-danger"></div> <!--UL list -->

                        <div class="flex-field">
                            <div class="flex-field-inner col-md-5">
                                <label>Duration: </label>
                                <span id="duration-min-span" class="range-nums"></span> <!--span that hold the value, set on slide action-->
                                <div id="slider-range-duration" class="col-md-6"></div> <!--slider-->
                                <span id="duration-max-span" class="range-nums"></span>
                                <input asp-for="DurationMinHoursFilter" type="text" id="duration-min" hidden> <!--hidden fields to send the values to the BE action-->
                                <input asp-for="DurationMaxHoursFilter" type="text" id="duration-max" hidden> <!--they are set on slide action-->
                            </div>

                            <div class="flex-field-inner col-md-7">
                                <label>Rank: </label>
                                <span id="rank-min-span" class="range-nums"></span>
                                <div id="slider-range-rank" class="col-md-7"></div>
                                <span id="rank-max-span" class="range-nums"></span>
                                <input asp-for="RankMinFilter" type="text" id="rank-min" hidden>
                                <input asp-for="RankMaxFilter" type="text" id="rank-max" hidden>
                            </div>
                        </div>
                        <div class="flex-field genre-sort-row">
                            <div class="flex-field-inner">
                                @if (Model.Genres != null)
                                {
                                    @for (int i = 0; i < Model.Genres.Count(); i++)
                                    {
                                        <div class="form-check">
                                            <label class="form-check-label" asp-for="@Model.Genres[i].IsSelected">
                                                <input class="form-check-input" type="checkbox" asp-for="@Model.Genres[i].IsSelected">
                                                @Model.Genres[i].Name&nbsp;
                                                <span class="form-check-sign">
                                                    <span class="check"></span>
                                                </span>
                                            </label>
                                        </div>
                                        <input type="hidden" asp-for="@Model.Genres[i].Id" />
                                        <input type="hidden" asp-for="@Model.Genres[i].Name" />
                                    }
                                }
                            </div>
                            <div class="filter-btns">
                                <div class="btn-group">
                                    <select asp-for="SortMethod" class="form-control text-dark btn-primary" asp-items="@Html.GetEnumSelectList<PlaylistGenerator.Web.Models.Playlist.SortMethod>()">
                                        @*<option selected>Sort</option>*@
                                    </select>
                                    <span asp-validation-for="SortMethod" class="text-danger"></span>
                                </div>

                                <div class="btn-group">
                                    <select asp-for="SortOrder" class="form-control text-dark btn-primary" asp-items="@Html.GetEnumSelectList<PlaylistGenerator.Web.Models.Playlist.SortOrder>()">
                                        @*<option selected>Order</option>*@
                                    </select>
                                    <span asp-validation-for="SortOrder" class="text-danger"></span>
                                </div>

                                <input type="submit" value="Filter" class="btn btn-outline-info" />
                            </div>
                        </div>
                        <partial name="_LoadingPartial" />
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-1 text-center border-left border-primary search-btn">
        <button class="btn btn-link" id="search-button" data-toggle="modal" data-target="#searchModal">
            <h3><i class="tim-icons icon-zoom-split"></i></h3>
            <span class="d-lg-none d-md-block">Search</span>
        </button>
    </div>
</div>
<br />

@if (Model.CurrentPage != 0 && Model.LastPage != Int32.MinValue)
{
    <partial name="_PageNavigatorPartial" model="@Model" />
}

<div class="row">
    @foreach (var item in Model.CollectionPlaylists)
    {
        <div class="col-lg-4">
            <div class="card p-3">
                <h4 class="text-center">@item.Name</h4>
                <div class="text-center">
                    <a href="@Url.Action("PlaylistById", "Playlists", new { id = item.Id })">
                        <img src="@item.Image" class="img-circle-lg" />
                    </a>
                </div>
                <p class="text-right">@item.UserName <a href="@Url.Action("UserById", "Users", new { id = item.UserId })"><img src="@item.UserImage" height="40" id="img-circle" /></a></p>
                <br />
                <p class="text-center"><i>@item.Description</i></p>
                <br />
                <p class="text-center"><b><i class="tim-icons icon-calendar-60"></i> Created:</b> @item.DateCreated.ToString().Split(' ').ToArray()[0]</p>
                <br />
                <div class="row text-center">
                    <div class="col-md-3 text-center"><p><i class="tim-icons icon-time-alarm"></i></p></div>
                    <div class="col-md-3 text-center"><p><i class="tim-icons icon-chart-bar-32"></i></p></div>
                    <div class="col-md-3 text-center"><p>Genres</p></div>
                    <div class="col-md-3 text-center"><p>Songs</p></div>
                </div>
                <div class="row text-center">
                    <div class="col-md-3 text-center"><p>@(item.DurationPlaylist / 60) min</p></div>
                    <div class="col-md-3 text-center"><p>@item.Rank.ToString("F0")</p></div>
                    <div class="col-md-3 text-center"><p>@item.GenresCount</p></div>
                    <div class="col-md-3 text-center"><p>@item.SongsCount</p></div>
                </div>
                <br />
                @if (User.IsInRole("Admin") || (User.Identity.Name == item.UserName && User.Identity.Name != null && item.UserName != null))
                {
                    <div class="text-center">
                        <button type="button" class="btn btn-primary btn-round" onclick="window.location='@Url.Action("Update", "Playlists", new { id = item.Id })'"><i class="tim-icons icon-pencil"></i></button>
                        @if (User.IsInRole("Admin"))
                        {
                            @if (item.IsUnlisted)
                            {
                                <button type="button" class="btn btn-success btn-round" onclick="window.location='@Url.Action("SwapUnlistedStatus", "Playlists", new { id = item.Id, isSwappedByAdmin = true, page = Model.CurrentPage })'"><i class="tim-icons icon-simple-add"></i></button>
                            }
                            else
                            {
                                <button type="button" class="btn btn-warning btn-round" onclick="window.location='@Url.Action("SwapUnlistedStatus", "Playlists", new { id = item.Id, isSwappedByAdmin = true, page = Model.CurrentPage })'"><i class="tim-icons icon-simple-remove"></i></button>
                            }
                        }
                        @{ 
                            item.IsToBeDeletedByAdmin = false;
                            item.NameController = "Playlists";
                            item.CurrentPage = Model.CurrentPage;
                        }
                        <partial name="_DeleteModalPartial" model="@item" />
                    </div>
                }
            </div>
        </div>
    }
</div>
<br />

@section Scripts {
    <script>
    $(document).ready(function () {
            $("#inlineFormInputGroup").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: "@Url.Action("AjaxMethod")",
                        data: { substring: document.getElementById('inlineFormInputGroup').value },
                        type: "POST",
                        success: function (data) {
                            response($.map(data, function (item) {
                                return item.name;
                            }))
                        },
                        error: function (response) {
                            alert(response.responseText);
                        },
                        failure: function (response) {
                            alert(response.responseText);
                        }
                    });
                },
                select: function (e, i) {
                    $("#inlineFormInputGroup").val(i.item.val);
                },
                minLength: 1,
                position: { my: "right top", at: "right bottom" }
            });
    })
    </script>
}

PlaylistGenerator/Web/PlaylistGenerator.Web/Views/Playlists/Update.cshtml
@model PlaylistGenerator.Web.Models.Playlist.PlaylistFullViewModel

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12 text-center">
        <h1>Update Playlist!</h1>
    </div>
</div>

<div class="row">
    <div class="col-lg-4"></div>
    <div class="col-lg-4">
        <div class="card p-3">
            <form asp-controller="Playlists" asp-action="Update" method="post" class="form" enctype="multipart/form-data">
                <div asp-validation-summary="All" class="text-danger"></div> <!--UL list -->

                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Description"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <hr />

                <label>Attach Image</label><br />
                <input type="file" name="ImageFile" class="btn btn-success btn-round"/>
                <hr />
                <button type="submit" class="btn btn-primary btn-round"><i class="tim-icons icon-send"></i></button>
            </form>
        </div>
    </div>
    <div class="col-lg-4"></div>
</div>