PlaylistGenerator/Web/PlaylistGenerator.Web/Controllers/ApiServicesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PlaylistGenerator.Web.Controllers
{
    public class ApiServicesController : Controller
    {
        public ApiServicesController()
        {

        }

        public async Task<IActionResult> General()
        {
            return await Task.Run(() => View());
        }

        public async Task<IActionResult> Documentation()
        {
            return await Task.Run(() => View());
        }
    }
}

PlaylistGenerator/Web/PlaylistGenerator.Web/Views/ApiServices/General.cshtml
@{
    ViewData["Title"] = "General";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">

</div>

<div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6 text-center">
        <a href="@Url.Action("General", "ApiServices")" class="btn btn-primary btn-round">Home</a>
        <a href="/swagger/index.html" target="_blank" class="btn btn-outline-info btn-round">Docs</a>
        <a href="/Identity/Account/Manage" class="btn btn-outline-info btn-round">API Key</a>
    </div>
    <div class="col-md-3 text-right"></div>
</div>
<br />

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header mb-1">
                <h5 class="card-category">REST API...</h5>
                <h3 class="card-title">Terms & Conditions</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-2 text-center">
                        <img src="~/images/rest_api_image_600x600.png" alt="admin_welcome" class="img-circle-lg" />
                    </div>
                    <div class="col-md-10">
                        <blockquote>
                            <div class="blockquote blockquote-primary">
                                <h4 class="text-success">Welcome to the API Services platform!</h4>
                                <p>The REST API leverages HTTP as a transport protocol and clear text JSON for the request and response payloads. Accessing the REST API is done through authentication.</p>
                                <p>API documentation is the information that is required to successfully consume and integrate with an API. We used Swagger to document ours. The following functionality is present:</p>
                                <ul>
                                    <li>Access playlists (both as a single item as well as a collection)</li>
                                    <li>Generate new playlists based on certain options (same options as per the private part)</li>
                                    <li>User can edit or delete his own existing playlists (same options as per the private part)</li>
                                </ul>
                            </div>
                        </blockquote>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-2 text-center">
                        <a href="/swagger/index.html" target="_blank" class="btn btn-primary btn-round">Docs</a>
                    </div>
                    <div class="col-md-10">
                        <blockquote>
                            <div class="blockquote blockquote-primary">
                                <p class="text-success">Documentation</p>
                                <p>The <a href="/swagger/index.html">Documentation</a> of our Web API Services is organized and generated via <a href="https://swagger.io/" target="_blank"><b>Swagger</b></a>, a product supported by SMARTBEAR.</p>
                                <p>It is easy to read, understandable and explicit.</p>
                            </div>
                        </blockquote>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-2 text-center">
                        <a href="/Identity/Account/Manage" class="btn btn-primary btn-round">API Key</a>
                    </div>
                    <div class="col-md-10">
                        <blockquote>
                            <div class="blockquote blockquote-primary">
                                <p class="text-success">API Key</p>
                                <p>To get access to the API Services, the users need to have a valid registration in the <a href="@Url.Action("Index", "Home")">PlaylistGenerator.Web</a> application.</p>

                                <div class="alert alert-info alert-with-icon" data-notify="container">
                                    <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close">
                                        <i class="tim-icons icon-simple-remove"></i>
                                    </button>
                                    <span data-notify="icon" class="tim-icons icon-bell-55"></span>
                                    <span data-notify="message">One User has access to generating only one <a href="/Identity/Account/Manage">API Key</a> per se.</span>
                                </div>
                                <p><a href="/Identity/Account/Manage">API Key</a> plays a role of a 'password'. It should be a part of the query string in each request to the API Server.</p>
                                <p><a href="/Identity/Account/Manage">API Key</a> is genereted from the 'Manage your account' page within the User's profile. Once in the 'Profile' section, an expandable button <b class="text-primary">⛛</b> appears next to 'API'. Press that to proceed.</p>
                                <p>If the user does not have an <a href="/Identity/Account/Manage">API Key</a> yet - clicking on the 'Generate' button would create a new Guid. This would be the unique key that the User can use to get access to our services.</p>
                                <p>Else, if the User already has an <a href="/Identity/Account/Manage">API Key</a> an option for re-'Generate' a new key is available.</p>
                                <div class="alert alert-warning alert-with-icon" data-notify="container">
                                    <button type="button" aria-hidden="true" class="close" data-dismiss="alert" aria-label="Close">
                                        <i class="tim-icons icon-simple-remove"></i>
                                    </button>
                                    <span data-notify="icon" class="tim-icons icon-time-alarm"></span>
                                    <span data-notify="message">Notice that generating a new <a href="/Identity/Account/Manage">API Key</a> overrides the existing key and replaces it with a new one. This makes the old API Key unus</span>
                                </div>
                            </div>
                        </blockquote>
                    </div>
                </div>
                <br />                
            </div>
        </div>
    </div>
</div>
<br />